### ISSUE TITLE
`gettp` use of cal and calibrate is inconsistent

### ISSUE THREAD

**Issue by astrofle** [GreenBankObservatory/dysh#133]
When calling `gettp` and using `cal=True`, the returned data is still a combination of the `cal='T'` and `cal='F'` rows.

An example:

``` Python
import numpy as np

from dysh.fits.gbtfitsload import GBTFITSLoad
import dysh.util as util

testdata = util.get_project_testdata()
data_path = testdata  / "AGBT18B_354_03/AGBT18B_354_03.raw.vegas/AGBT18B_354_03.raw.vegas.A.fits"

sdf = GBTFITSLoad(data_path, verbose=False)
tps = sdf.gettp(6, ifnum=2, cal=True, plnum=0)

# This should return True -- it does not.
np.all(tps[0]._refcalon == tps[0].total_power(0).flux.value)

# This should return False -- it does not.
np.all(0.5*(tps[0]._refcalon + tps[0]._refcaloff) == tps[0].total_power(0).flux.value)
```

**Comment by mpound** [comment]
I find the GBTIDL documentation about cal_state and sig_state confusing:
https://www.gb.nrao.edu/GBT/DA/gbtidl/release/user/guide/gettp.html

It seems like regardless of cal_state/sig_state,  dototalpower is called to average both switching phases cal_state=0/1 ('F'/'T' in SDFITS header) and calculate Tsys.  But then some different average is done (keeping the original Tsys?) depending on cal_state & sig_state being 0,1, or unset.  

Specifically, I am having trouble parsing this sentence in the GBTIDL **Summary** of gettp:

_**Note:** this step is done even when the data from only one state is requested using the cal_state or sig_state keywords._

Here is my best guess at the expected behavior,  with Python representation 0=False, 1=True, None=unset:

 | CAL     |   SIG    |   RESULT |     TSYS
 | -----      |  -------   |  --------    |    ----  | 
 |  None  | None |    data = 0.5* (REFCALON + REFCALOFF) , regardless of sig state  | use all CAL states, all SIG states |
 | None  | True |      data = 0.5* (REFCALON + REFCALOFF), where sig = 'T'  (sig_state=1) |  use all CAL states, SIG='T' |
| None  | False |     data = 0.5* (REFCALON + REFCALOFF), where sig = 'F'  (sig_state=0) |  use all CAL states, SIG='F' |
| True   |   None |    data = REFCALON, regardless of sig_state | use all CAL states, all SIG states |
| False |   None  |  data = REFCALOFF, regardless of sig_state | use all CAL states, all SIG states |
 | True   | True  |  data = REFCALON, where sig='T' (sig_state=1) |  use all CAL states, SIG='T' |
 | True   | False | data = REFCALON, where sig='F' (sig_state=0) | use all CAL states, SIG='F' |
 | False  | True |  data = REFCALOFF  where sig='T' (sig_state=1) |use all CAL states, SIG='T' |
 | False  | False |  data = REFCALOFF, where sig='F' (sig_state=0) |use all CAL states, SIG='F' |

While the TSYS column of the above table seems to match the last bullet point of the GBTIDL summary, the actual behavior of GBTIDL does not?   

```
filein,"TGBT21A_504_01.raw.vegas"
gettp,20,sig_state=1
  Tsys:  27.21
gettp,20,sig_state=1,cal_state=0
  Tsys:  27.22
gettp,20,sig_state=1,cal_state=1
  Tsys:  27.20

```
I would expect Tsys would be the same in all three commands.
