### ISSUE TITLE
version and tag / naming convention

### ISSUE THREAD

**Issue by teuben** [GreenBankObservatory/dysh#2]
As Marc just wrapped up his version, I'd like to suggest we (git) tag it, or are we following milestone tags? If so, where are those documented. Maybe we need a roadmap.rst somewhere?

E.g.

       cat src/dysh/__init__.py 

shows we are now in version 0.1.0a2.

I was tempted to add a git tag, but I'll wait until we agreed when to do it, and the naming convention.

**Comment by mpound** [comment]
I agree, we need a convention for versions and should always tag releases.   We probably only need major.minor and don't need the patch digit?  I like using "a" and "b" for alpha/beta releases because the downstream sites PyPi and readthedocs automatically recognize them as not full releases.  I have neglected to tag thus far but will do so going forward.

**Comment by mpound** [comment]
we have agreed on major.minor.path{a,b,rcN}
