### ISSUE TITLE
old GBTIDL example files don't work in dysh yet

### ISSUE THREAD

**Issue by teuben** [GreenBankObservatory/dysh#216]
**Describe the bug**

Older GBTIDL example fields failed on GBTFITSLoad()   [obviously not urgent, but good to fix in the end]

**How to Reproduce**
 
I grabbed the examples files:

Example 1 (PS)
http://safe.nrao.edu/wiki/pub/GB/Data/GBTIDLExampleAndSampleData/ngc5291.fits

Example 2 (FS)
http://safe.nrao.edu/wiki/pub/GB/Data/GBTIDLExampleAndSampleData/W3OH.fits

Example 3 (TP nod) 
http://safe.nrao.edu/wiki/pub/GB/Data/GBTIDLExampleAndSampleData/IC1481.fits

and tried things like:

f4 = util.get_project_testdata() / 'W3OH.fits'
sdf4 = GBTFITSLoad(f4)
AttributeError: 'Selection' object has no attribute 'TIMESTAMP'

Admittedly, these are the old examples, but it's good to understand where/why we ran into this TIMESTAMP issue, and can it be easily fixed?

**Environment**

Current dysh, ubuntu linux. But should not depend on it.

**Comment by astrofle** [comment]
My bad. I see now that the example files do not work. However, the original data works. You can find the original data here:
[ngc5291](https://www.gb.nrao.edu/dysh/acceptance_testing/data/AGBT05B_047_01/AGBT05B_047_01.raw.acs/AGBT05B_047_01.raw.acs.fits) and [W3OH+IC1481](https://www.gb.nrao.edu/dysh/acceptance_testing/data/TREG_050627/TREG_050627.raw.acs/TREG_050627.raw.acs.fits).

**Comment by astrofle** [comment]
Update examples in the GBTIDL wiki page, and provide definite answer as to why the old files do not work on dysh.

**Comment by astrofle** [comment]
The SDFITS files in the [`GBTIDL` user's guide](https://www.gb.nrao.edu/GBT/DA/gbtidl/users_guide/node72.html) examples used version 1.2 of the SDFITS filler, and FITS definition 1.2. The current SDFITS filler is 1.22 and the FITS definition is 1.9. That explains why the old SDFITS files don't work in `dysh`.

At version [1.4 of sdfits](https://safe.nrao.edu/wiki/bin/view/GB/Data/SdfitsReleaseNotes_1_4) the Hanning smoothing was turned ff by default, this could have caused part of the difference observed, see below. As part of the later releases, additional columns were added to the SDFITS files. That explains why `dysh` cannot handle the 1.2 version of the SDFITS files.

I ran the example using version 1.2 and 1.22 of the files and compared the results. 

- For the ngc5291 data set there are differences at the 10 mK level (probably smaller, but only appreciated at this level due to rounding) between the two versions, and the difference between the two resulting spectra has a mean of 0.13 mK, a maximum of 6.46 mK and a minimum of -12.94 mK.

- For W3OH the differences are larger, ~30 K, but the mean difference is smaller, ~1e-8 K.

I'll update the data sets in the `GBTIDL` examples and close this issue.
