### ISSUE TITLE
frequencyswitch notebook data path

### ISSUE THREAD

**Issue by astrofle** [GreenBankObservatory/dysh#244]
**Describe the bug**
The frequency switch notebook uses `util.get_project_testdata()` to set the data path. However, this path is not valid if `dysh` was installed through `pip`.

**How to Reproduce**
Try to run the frequency switched notebook with `dysh` installed from `pip`.

**Comment by teuben** [comment]
yes, this was a deliberate error since I didn't know where these files are to be located on the GBO system.  I think that should be documented in our README file in testdata.
I'm also inclined to have some kind of environment variable ($DYSH_EXAMPLE_DATA) where off-site people can bypass the expensive wget commands to grab big files. At UMD we have a shadow tree already, but no documentation how it can be maintained via some rsync.  

The first thing I need to know if where on the gbo system the dysh/example_data tree is ?

**Comment by teuben** [comment]
We had an old  discussion about this, see #11 and #139

I have this kind of function in my mind, which covers finding local file, local example_data tree and wgettable file

filename = dysh_example_data("TGBT21A_501_11.raw.vegas.fits", "dysh/example_data/onoff-L/data", mode="wget")
if filename == None:
      cannot find that file, or use try/except?

**Comment by astrofle** [comment]
The data can be found in: http://www.gb.nrao.edu/dysh/example_data/fs-L/data/AGBT20B_014_03.raw.vegas/AGBT20B_014_03.raw.vegas.A.fits

I created a new SDFITS without the trimming you had done (the file is only ~23 MB). I'll let @teuben or @mpound change the notebook. For now (beta release 0.3.0), I think we should stick to what Marc has been doing using `wget`.
